apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kyc-app
  template:
    metadata:
      labels:
        app: kyc-app
    spec:
      containers:
        - name: kyc-app
          image: your-docker-registry/kyc-platform:latest  # Replace with your actual image
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: kyc-platform-config
            - secretRef:
                name: kyc-platform-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi